// Generated by Wrangler on Thu Sep 12 2024 13:31:59 GMT+0800 (China Standard Time)
// by running `wrangler types`

interface Env {
	AWS_REGION: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	RESEND_API_KEY: string;
	API_AUTH_TOKEN: string;
	DB: D1Database;
}
