// Generated by Wrangler on Wed Jul 31 2024 10:31:50 GMT+0800 (中国标准时间)
// by running `wrangler types`

interface Env {
    AWS_REGION: string;
    AWS_ACCESS_KEY_ID: string;
    AWS_SECRET_ACCESS_KEY: string;
    API_AUTH_TOKEN: string;
}
