// Generated by Wrangler by running `wrangler types`

interface Env {
	AWS_REGION: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	RESEND_API_KEY: string;
	MAILERSEND_API_KEY: string;
	API_AUTH_TOKEN: string;
	DB: D1Database;
}
